version: 2
jobs:
  test:
    working_directory: ~/api
    docker:
        - image: circleci/node:dubnium
        - image: ibmcom/cloudant-developer
        - image: redis:latest

    environment:
      COUCH_PROTOCOL: 'http:'
      COUCH_HOST: 127.0.0.1
      COUCH_PORT: 5984
      COUCH_ADMIN_USERNAME: admin
      COUCH_ADMIN_PASSWORD: pass
      COUCH_AUTH_DB: _users
      DB_NAME: test-api
      COUCH_LOG_DB: log
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      AWS_REGION: us-east-1

    steps:
      - checkout
      - run: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - run: sudo apt update
      - run: sudo apt-get install -y graphicsmagick imagemagick libreoffice
      - run: if [[ ! -e ffmpeg-static ]]; then wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz && mkdir ffmpeg-static && tar -vxf ffmpeg-release-amd64-static.tar.xz -C ffmpeg-static --strip-components=1; fi
      - run: sudo cp ffmpeg-static/{ffmpeg,ffprobe} /usr/bin/
      - restore_cache:
          keys:
            - v2-node_modules-{{ checksum "package-lock.json" }}
            - v2-node_modules-
      - run:
          command: npm install
          no_output_timeout: 5m
      - save_cache:
          key: v2-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
      - persist_to_workspace:
          root: ~/api
          paths: .

  publish:
    working_directory: ~/api
    docker:
      - image: circleci/node:dubnium
    steps:
      - attach_workspace:
          at: ~/api
      - run:
          name: Authenticate with registry
          command: echo '//registry.npmjs.org/:_authToken='$NPM_PRIVATE_AUTH_TOKEN > $HOME/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:  # required since `publish` has tag filters AND requires `test`
            tags:
              only: /.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
